language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
before_install:
  - sudo apt-get install nodejs; node --version
install:
  - pip install -U coverage requests six websocket-client
  - npm install -G socket.io
before_script:
  - DEBUG=* node socketIO_client/tests/serve.js &
  - sleep 1
script: nosetests
